server:
  port: 8080
spring:
  servlet:
    multipart:
      #限制文件大小
      max-file-size: 100MB
      max-request-size: 150MB
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: liushengjun97@163.com
    password: JEXYRMLTSLRGDWNE
    port: 465
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: true
            required: true
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  redis:
    host: localhost
    database: 1
    port: 6379
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.demo.entity